### ISSUE TITLE
Imported file with meshes opened only as empty

### ISSUE THREAD

**Issue by dommyx** [nrgsille76/io_scene_max#19]
Hi, thank you so much for the great plugin :)
I ran into a bug, a friend of mine works in Max and sent me a file that I can't import, or rather it only imports empty, not meshes. I tried to open it in the online max files viewer and it already shows up there.
Do you know what is the problem? I also tried different import settings and nothing changed.
But when I tried a different model in the .max file it works, only this one only imports empty.

3D model: https://we.tl/t-VomtgRuniX
3D max viewer: https://autode.sk/3Z7mDWT

Thank you very much :)

**Comment by nrgsille76** [comment]
@dommyx  I checked the file, the models wich are included are not mesh objects but primitives like box, sphere or cylinder. Creating primitives was not yet included into the script, I will add this to the newest version 1.5.5
I updated the script to import the primitives box, cylinder and uv sphere but because there may be modifiers aplied, it may not look like the original file.

**Comment by nrgsille76** [comment]
@dommyx  yes the modifiers have to be applied to mesh, in Blender the option would be `Object > Apply > Visual Geometry to Mesh`
