### ISSUE TITLE
can not activate the add-on in Blender 4.1

### ISSUE THREAD

**Issue by qb-ben** [nrgsille76/io_scene_max#5]
I use the Windows version 4.1 of Blender.
I installed the add-on and the script appears in the script/add-on files of blender (AppData/Roaming/Blender Foundation), However the add-on is not visible in the Preferences /Add-on menu of Blender, and cannot be activated.

**Comment by nrgsille76** [comment]
@qb-ben  That is because this version has no blender info (bl_info) and can only be used as extension for Blender 4.2. 
For blender 4.1 you need the add-on version, it can be found in my other repository [blender_io_addons](https://github.com/nrgsille76/blender-io-addons), there is also a LTS version available for the latest Blender 3.6 LTS
